### ISSUE TITLE
Want PR? Cosine similarity function for TFIDF(S)

### ISSUE THREAD

**Issue by DTrejo** [NaturalNode/natural#337]
Thanks so much for `natural`, I've found it very helpful :)

Right now, similarity for a phrase is calculated by adding the tfidf scores together for each word. If you were to rank them, the most similar one would have the largest score. 

For a phrase, the "direction" of the words being similar to the "direction" of the words in each document is what I'd like to know and should give better relevancy. This can be done with a vector model and [cosine similarity][1]. To do this, I think I'd need to write two new functions: `TfIdf.prototype.tfidfsVector` and `TfIdf.prototype.tfidfVector`. I'm not particularly happy with the names yet.

How much would you welcome a PR along these lines? If you're not interested that's okay too.

Thanks again,  
David

[1]:https://en.wikipedia.org/wiki/Cosine_similarity

---

###### Related implementations
- https://github.com/mpalmerlee/covectric
- https://github.com/compute-io/cosine-similarity

**Comment by DTrejo** [comment]
Here is what I would add to `tfidf.js`

###### TODO:
- [ ] make style match
- [ ] move tests to the tfidf spec
- [ ] better naming
- [ ] better API - sorting should be optional or done in userspace.
- [ ] anything else?

```js
TfIdf.prototype.tfidfVector = function(terms, d) {
    var _this = this;

    if(!_.isArray(terms))
        terms = tokenizer.tokenize(terms.toString().toLowerCase());

    return terms.map(function(term) {
        var idf = _this.idf(term);
        idf = idf === Infinity ? 0 : idf;
        return (tf(term, _this.documents[d]) * idf);
    });
};

TfIdf.prototype.tfidfsVector = function(terms, callback) {
    var tfidfs = new Array(this.documents.length);

    for(var i = 0; i < this.documents.length; i++) {
        tfidfs[i] = this.tfidfVector(terms, i);

        if(callback)
            callback(i, tfidfs[i], this.documents[i].__key);
    }

    return tfidfs;
};

var similarity = require('compute-cosine-similarity')

// returns document array, sorted by cosine similarity to the terms
TfIdf.prototype.tfidfsCosine = function(terms, callback) {

    // build tfidf terms vector:
    // [ tfidf(term1, terms), ... , tfidf(termN, terms) ]
    var termDoc = buildDocument(terms);
    var termVec = [];
    var numDocuments = 1;
    var docsWithTerm = 1;
    for(var term in termDoc) {
        if('__key' === term) continue
        var idf = 1 + Math.log(numDocuments / ( 1 + docsWithTerm ));
        termVec.push(tf(term, termDoc) * idf);
    }

    // build tfidf terms vector for each doc
    var tfidfsVecs = new Array(this.documents.length);

    for(var i = 0; i < this.documents.length; i++) {
        tfidfsVecs[i] = this.tfidfVector(terms, i);
        tfidfsVecs[i].cosine = similarity(termVec, tfidfsVecs[i]);
        tfidfsVecs[i].i = i

        if(callback)
            callback(i, tfidfsVecs[i], this.documents[i].__key);
    }

    var sorted = tfidfsVecs.sort(function(a, b) {
        return b.cosine - a.cosine;
    })
    return sorted
};

if (!module.parent) test();

function test() {
    var Tfidf = module.exports;
    var tfidf = new Tfidf();

    // example from https://janav.wordpress.com/2013/10/27/tf-idf-and-cosine-similarity/
    tfidf.addDocument('The game of life is a game of everlasting learning'.toLowerCase().split(' '));
    tfidf.addDocument('The unexamined life is not worth living'.toLowerCase().split(' '));
    tfidf.addDocument('Never stop learning'.toLowerCase().split(' '));

    console.log(tfidf.listTerms(0));
    console.log(tfidf.listTerms(1));
    console.log(tfidf.listTerms(2));

    var sorted = tfidf.tfidfsCosine('life learning');
    console.log('sorted', sorted);
    console.assert(sorted[0].i == 0);
    console.assert(sorted[1].i == 1);
    console.assert(sorted[2].i == 2);
    console.assert(sorted[1].cosine == sorted[2].cosine);
}
```

**Comment by kkoch986** [comment]
@DTrejo i think this would make a great addition! i also think the steps you outlined seemed reasonable i would just add a step for adding some documentation of this feature in the README. i would say if theres no mention of it in the readme it tends to disappear.

thanks! going to close this for now just trying to clean up the issues a bit. looking forward to the PR!
